### ISSUE TITLE
would love to test it out, dm me on discord

### ISSUE THREAD

**Issue by regiments** [hashsha1/FiveM-Anticheat-RiotShield#1]
Callum#0500

personally i dont cheat but would love to get some inspriation and see your methods, idk if your selling source or allowing. trusted developers to test

**Comment by hashsha1** [comment]
Hello Callum,
the Source is of course Encrypted for Security Reasons.

**Comment by regiments** [comment]
thats fine mate, just give me an add and we can chat about me testing the encrypted source mgith have a business offer with it.

**Comment by regiments** [comment]
is this not possible no, can you maybe help me make my own anticheat and point me in directions?
